-- 연락처별 미팅 이력 테이블 (메모 포함)
CREATE TABLE IF NOT EXISTS meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
    met_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    memo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 인덱스 추가 (조회 성능)
CREATE INDEX IF NOT EXISTS idx_meetings_contact_id ON meetings(contact_id);
